name: Enforce License Compliance

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fossas/fossa-action@v1.1.0
        with:
          api-key: ${{secrets.fossaApiKey}}
